#!/bin/bash
PREFIX=/opt/pkgr
NPROC=$(nproc)

if [[ -z $1 ]]; then
    echo "no blueprint specified"
    exit
fi

eval "$(cat $1)"
rm -rf build/*
wget -O build/package "$source"
cd build
if [[ -n $(file package | grep "Zip archive data") ]]; then
    unzip package
fi
if [[ -n $(file package | grep "compressed data") ]]; then
    tar xf package
fi
rm package
cd *
for step in "${steps[@]}"; do
    eval $step;
done
